GET http://localhost:3001/documents

###

POST http://localhost:3001/document/new
Content-Type: application/json

{
    "documentType": "ICS",
    "uploaderName": "Jennifer dela Cruz",
    "description": "This is a laptop",
    "dateAcquired": "Sat Nov 28 2020 22:57:38 GMT+0530 (India Standard Time)" ,
    "quantity": 1

}

###
POST http://localhost:3001/admin/create
Content-Type: application/json

{
    "username": "Admin",
    "password": "adminPassword12345"

}

###
DELETE http://localhost:3001/document/delete/6628dae621a12701734f912b

###

POST http://localhost:3001/admin/signin
Content-Type: application/json

{
    "username": "admin2",
    "password": "adminPass"
}

###
GET http://localhost:3001/admins